---
title: "Microbesomics - MetS Metagenomic Signature"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, results="asis")
```

```{r}
#Import librerie R
library(ggplot2)
library(DESeq2)
library(vegan)
library(ggVennDiagram)
require(gridExtra)
library(UpSetR)
library(ComplexUpset)
library(dplyr)
library(tidyr)
library(plyr)
library(ComplexHeatmap)
library(circlize)
library(png)
library(knitr)
library(Microsoft365R)
library(microbiomeMarker)
library(phyloseq)
library(xlsx)
library(reticulate)
use_condaenv("python_env")

py_run_string("
import pandas as pd
import numpy as np
import statsmodels.formula.api as sm
import pingouin as ping           
")
```

```{r}
#Per Gestire il problema dei NA li sostitutiamo con "unknown"
mtbDt = readRDS("../data/metabolomics/mtbDt5vs6.rds")
smpDt = readRDS("../data/clinics/sampleDt5vs6.rds")
smpDt = as.data.frame(smpDt)

# Conta le occorrenze per ogni paziente (pz)
pz_counts <- table(smpDt$pz)

# Seleziona quelli con almeno 2 conteggi
toKeep <- names(pz_counts[pz_counts >= 2])

# Filtra il dataset originale
smpDt <- smpDt[smpDt$pz %in% toKeep, ]
mtbDt <- mtbDt[match(row.names(smpDt), row.names(mtbDt)), ]
```



```{r}
metdiffpath = "../results/metabolomics/DifferentialAnalysis/TtestMetabolomic.xlsx"

metAll = as.data.frame(mtbDt)

metAll$groupIGA = as.factor(smpDt$`GROUP IGA`)

cmps = c()
tpval = c()
nTot = c()
nNom = c()
meanNom = c()
stNom = c()
nDen = c()
meanDen = c()
stDen = c()
logFc = c()
nom = "6"
den = "5"
meTmp = metAll[metAll$groupIGA %in% c(nom, den),]
for (cmp in colnames(metAll)) {
  if (!cmp %in% "groupIGA") {
    
 test_result <- NULL
tryCatch({
  test_result <- wilcox.test(meTmp[,cmp] ~ meTmp[,"groupIGA"], meTmp)
}, error = function(e) {
  cat("Error in processing column", cmp, ": ", e$message, "\n")
})
if (!is.null(test_result)) {
  tpval = append(tpval, test_result$p.value)
} else {
  tpval = append(tpval, NA)  # Se c'è un errore, metti NA
}
    
    cmps = append(cmps, cmp)
    #tpval = append(tpval, test_result$p.value)
    nTot = append(nTot, nrow(meTmp))
    nomTmp = meTmp[meTmp[,"groupIGA"] == nom,]
    nNom = append(nNom, nrow(nomTmp))
    meanNom = append(meanNom, mean(nomTmp[,cmp]))
    stNom = append(stNom, sd(nomTmp[,cmp]))
    
    
    denTmp = meTmp[meTmp[,"groupIGA"] == den,]
    nDen = append(nDen, nrow(denTmp))
    meanDen = append(meanDen, mean(denTmp[,cmp]))
    stDen = append(stDen, sd(denTmp[,cmp]))
    lfc = (mean(nomTmp[,cmp]) - mean(denTmp[,cmp]))
    logFc = append(logFc, lfc  )
    
  }

}
tpval = as.numeric(tpval)
fdr = p.adjust((tpval), method = "fdr")
logFct = log2(abs(logFc))
logFc = (logFc)
res = NA
res = cbind(cmps,nTot, nNom,meanNom, stNom, nDen, meanDen, stDen,logFc, tpval, fdr)
res = as.data.frame(res)
colnames(res) = c("cmps", "n",paste0("n_",nom), paste0("mean_",nom), paste0("StDev_",nom), paste0("n_",den), paste0("mean_",den), paste0("StDev",den), "logFc", "p-value", "fdr")

res = res[(res$"p-value") != NaN,]
res = res[order(res$"p-value"),]
#xlsx::write.xlsx(res,metdiffpath, sheetName = var,  append = T)

res$log2FC <- log2(
  (as.numeric(res[[paste0("mean_", nom)]]) + 1e-6) /
  (as.numeric(res[[paste0("mean_", den)]]) + 1e-6)
)


res
View(res)
```

```{r}
library(ggplot2)
library(ggrepel)

# Assumiamo che res sia già un data.frame con colonne "cmps", "logFc", "fdr"
df <- res
df$logFc <- as.numeric(as.character(df$logFc))
df$fdr   <- as.numeric(as.character(df$fdr))

alpha <- 0.05
df$negLogFDR <- -log10(df$fdr)
df$Signif <- ifelse(df$fdr <= alpha, "Significant", "Not Significant")

# Volcano plot
p <- ggplot(df, aes(x = logFc, y = negLogFDR, color = Signif)) +
  geom_point(alpha = 0.8, size = 2) +
  scale_color_manual(values = c("Not Significant" = "grey70",
                                "Significant" = "red")) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = -log10(alpha), linetype = "dashed") +
  theme_bw(base_size = 14) +
  labs(
    title = "Volcano plot - Metabolomics",
    x = paste0("log2 Fold Change (", nom, " vs ", den, ")"),
    y = "-log10(FDR)",
    color = ""
  )

# Etichette su tutti i significativi
p <- p + ggrepel::geom_text_repel(
  data = subset(df, fdr <= alpha),
  aes(label = cmps),
  size = 3,
  max.overlaps = 50,
  box.padding = 0.4,
  show.legend = FALSE
)

print(p)

# Se vuoi salvare:
# ggsave("volcano_metabolomics.png", p, width = 8, height = 6, dpi = 300)

```


```{r}
library(ggplot2)
library(ggrepel)

# assicurati che siano numerici
res$`p-value` <- suppressWarnings(as.numeric(res$`p-value`))
res$fdr       <- suppressWarnings(as.numeric(res$fdr))
res$log2FC    <- suppressWarnings(as.numeric(res$log2FC))

res <- res[!is.na(res$`p-value`) & !is.na(res$fdr) & !is.na(res$log2FC), , drop = FALSE]

alpha <- 0.05
res$negLogFDR <- -log10(pmax(res$fdr, .Machine$double.xmin))

# categorizziamo
res$ColorCat <- "NotSig"
res$ColorCat[res$fdr <= alpha & res$log2FC > 0] <- "Up"
res$ColorCat[res$fdr <= alpha & res$log2FC < 0] <- "Down"

cols <- c("NotSig" = "grey70", "Up" = "blue", "Down" = "red")

p <- ggplot(res, aes(x = log2FC, y = negLogFDR, color = ColorCat)) +
  geom_point(alpha = 0.9, size = 2) +
  scale_color_manual(values = cols) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = -log10(alpha), linetype = "dashed") +
  theme_bw(base_size = 14) +
  labs(
    title = paste0("Volcano plot - Metabolomics (", nom, " vs ", den, ")"),
    x = paste0("log2 Fold Change (", den, "/", nom, ")"),
    y = "-log10(FDR)",
    color = ""
  ) +
  ggrepel::geom_text_repel(
    data = subset(res, fdr <= alpha),
    aes(label = cmps),
    size = 3,
    max.overlaps = 100,
    box.padding = 0.4,
    show.legend = FALSE
  )

p

```



